2025-10-18 23:13:02,259 [ERROR] app: Exception on /users [GET]
Traceback (most recent call last):
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\app\utils\roles.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\app\users\routes.py", line 15, in list_users
    return render_template("users/list.html", users=users)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\templates\users\list.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\templates\base.html", line 137, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\templates\users\list.html", line 69, in block 'content'
    <i class="fa fa-calendar-alt"></i> {{ _('Monthly Resolution Rate %') }}
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\ext.py", line 168, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\ext.py", line 180, in gettext
    return rv % variables  # type: ignore
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\markupsafe\__init__.py", line 165, in __mod__
    return self.__class__(super().__mod__(value))
ValueError: incomplete format
2025-10-18 23:13:57,239 [ERROR] app: Exception on /users [GET]
Traceback (most recent call last):
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\app\utils\roles.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\app\users\routes.py", line 15, in list_users
    return render_template("users/list.html", users=users)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\templates\users\list.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\templates\base.html", line 137, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\templates\users\list.html", line 69, in block 'content'
    <i class="fa fa-calendar-alt"></i> {{ _('Monthly Resolution Rate %') }}
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\ext.py", line 168, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\jinja2\ext.py", line 180, in gettext
    return rv % variables  # type: ignore
  File "C:\Users\ioannisb\Documents\Python-Development\IT\helpdesk_pro\.venv\lib\site-packages\markupsafe\__init__.py", line 165, in __mod__
    return self.__class__(super().__mod__(value))
ValueError: incomplete format
2025-10-18 23:15:16,730 [INFO] app: Helpdesk Pro started
2025-10-18 23:15:17,925 [INFO] app: Helpdesk Pro started
2025-10-18 23:17:41,339 [INFO] app: Helpdesk Pro started
2025-10-18 23:17:42,578 [INFO] app: Helpdesk Pro started
2025-10-18 23:18:34,739 [INFO] app: Helpdesk Pro started
2025-10-18 23:18:35,898 [INFO] app: Helpdesk Pro started
2025-10-18 23:19:37,147 [INFO] app: Helpdesk Pro started
2025-10-18 23:19:38,331 [INFO] app: Helpdesk Pro started
2025-10-18 23:21:15,724 [INFO] app: Helpdesk Pro started
2025-10-18 23:21:16,881 [INFO] app: Helpdesk Pro started
2025-10-18 23:21:49,880 [INFO] app: Helpdesk Pro started
2025-10-18 23:21:51,036 [INFO] app: Helpdesk Pro started
2025-10-18 23:22:12,402 [INFO] app: Helpdesk Pro started
2025-10-18 23:22:13,578 [INFO] app: Helpdesk Pro started
2025-10-18 23:22:55,828 [INFO] app: Helpdesk Pro started
2025-10-18 23:22:56,987 [INFO] app: Helpdesk Pro started
2025-10-18 23:23:43,272 [INFO] app: Helpdesk Pro started
2025-10-18 23:23:44,572 [INFO] app: Helpdesk Pro started
2025-10-18 23:24:22,779 [INFO] app: Helpdesk Pro started
2025-10-18 23:24:23,982 [INFO] app: Helpdesk Pro started
2025-10-18 23:24:42,257 [INFO] app: Helpdesk Pro started
2025-10-18 23:24:43,436 [INFO] app: Helpdesk Pro started
2025-10-18 23:25:02,657 [INFO] app: Helpdesk Pro started
2025-10-18 23:25:03,798 [INFO] app: Helpdesk Pro started
2025-10-18 23:26:17,079 [INFO] app: Helpdesk Pro started
2025-10-18 23:26:18,250 [INFO] app: Helpdesk Pro started
2025-10-18 23:26:41,154 [INFO] app: Helpdesk Pro started
2025-10-18 23:26:42,323 [INFO] app: Helpdesk Pro started
2025-10-18 23:27:30,614 [INFO] app: Helpdesk Pro started
2025-10-18 23:27:31,766 [INFO] app: Helpdesk Pro started
2025-10-18 23:29:58,110 [INFO] app: Helpdesk Pro started
2025-10-18 23:29:59,213 [INFO] app: Helpdesk Pro started
2025-10-18 23:32:16,888 [INFO] app: Helpdesk Pro started
2025-10-18 23:32:17,997 [INFO] app: Helpdesk Pro started
2025-10-18 23:32:48,073 [INFO] app: Helpdesk Pro started
2025-10-18 23:32:49,468 [INFO] app: Helpdesk Pro started
2025-10-18 23:35:37,492 [INFO] app: Helpdesk Pro started
2025-10-18 23:35:38,636 [INFO] app: Helpdesk Pro started
2025-10-18 23:36:33,624 [INFO] app: Helpdesk Pro started
2025-10-18 23:36:34,714 [INFO] app: Helpdesk Pro started
2025-10-19 00:05:19,507 [INFO] app: Helpdesk Pro started
2025-10-19 00:05:20,637 [INFO] app: Helpdesk Pro started
2025-10-19 00:08:00,223 [INFO] app: Helpdesk Pro started
2025-10-19 00:08:01,393 [INFO] app: Helpdesk Pro started
2025-10-19 00:12:17,379 [INFO] app: Helpdesk Pro started
2025-10-19 00:12:30,241 [INFO] app: Helpdesk Pro started
2025-10-19 00:13:14,777 [INFO] app: Helpdesk Pro started
2025-10-19 00:13:15,915 [INFO] app: Helpdesk Pro started
2025-10-19 00:14:02,815 [INFO] app: Helpdesk Pro started
2025-10-19 00:15:04,751 [INFO] app: Helpdesk Pro started
2025-10-19 00:15:05,839 [INFO] app: Helpdesk Pro started
2025-10-19 00:16:35,943 [INFO] app: Helpdesk Pro started
2025-10-19 00:20:44,574 [INFO] app: Helpdesk Pro started
2025-10-19 00:20:45,767 [INFO] app: Helpdesk Pro started
2025-10-19 00:24:17,822 [INFO] app: Helpdesk Pro started
2025-10-19 00:24:18,988 [INFO] app: Helpdesk Pro started
2025-10-19 00:25:28,158 [INFO] app: Helpdesk Pro started
2025-10-19 00:29:43,280 [INFO] app: Helpdesk Pro started
2025-10-19 00:29:47,735 [INFO] app: Helpdesk Pro started
2025-10-19 00:31:36,955 [INFO] app: Helpdesk Pro started
2025-10-19 00:32:22,104 [INFO] app: Helpdesk Pro started
